apply plugin: 'com.android.application'
if (!rootProject.ext.agpVersion.startsWith('9.')) {
    apply plugin: 'kotlin-android'
    apply plugin: 'kotlin-kapt'
}

android {
    compileSdk = (findProperty('compileSdk') ?: 34) as Integer

    namespace "com.fataar.demo"

    compileOptions {
        sourceCompatibility 17
        targetCompatibility 17
    }

    defaultConfig {
        applicationId "com.fataar.demo"
        minSdk = (findProperty('minSdk') ?: 19) as Integer
        targetSdk = (findProperty('targetSdk') ?: 34) as Integer
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding = true
    }

    if (!rootProject.ext.agpVersion.startsWith('9.')) {
        kotlinOptions {
            jvmTarget = "17"
        }
    }
}

repositories {
    flatDir {
        dirs 'libs/'
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation('androidx.appcompat:appcompat:1.6.1')
    implementation(name: 'fat-aar-final', ext: 'aar')
}
